import type { CustomModuleIconName } from "./icons";

/**
 * Our own words for each custom-module icon: what someone tracking their life
 * is likely to type when they want it -- "rego" for the car, "dentist" for the
 * stethoscope, "subscription" for the repeat arrows. Searched ahead of
 * Lucide's own tags (icon-tags.json), which cover the generic synonyms but
 * not life admin, and are sometimes noisy.
 *
 * Typed as a record over every icon name, so adding an icon to icons.tsx
 * without giving it words here doesn't compile. Lower case; a phrase may be
 * several words.
 */
export const ICON_KEYWORDS = {
  // The originals.
  package: ["parcel", "delivery", "item", "stuff", "general", "misc"],
  box: ["container", "items", "inventory", "collection", "stuff"],
  home: ["house", "property", "household", "rent", "mortgage", "real estate"],
  heart: ["favourites", "love", "wishlist", "saved", "special"],
  book: ["books", "reading", "read", "novel", "study"],
  palette: ["art", "colour", "color", "painting", "drawing", "design"],
  fitness: ["gym", "workout", "exercise", "weights", "training"],
  travel: ["trip", "holiday", "vacation", "flight", "flights", "airport", "abroad"],
  food: ["meals", "eating", "restaurant", "dining", "menu", "lunch", "dinner"],
  pet: ["pets", "animal", "vet", "paw"],
  wardrobe: ["clothes", "clothing", "outfits", "fashion", "shirt"],
  gifts: ["present", "presents", "birthday", "christmas", "wishlist"],
  games: ["gaming", "video games", "console", "playstation", "xbox", "nintendo"],
  learning: ["study", "course", "university", "uni", "degree", "education", "class"],
  work: ["job", "career", "office", "business", "employment"],
  shopping: ["shop", "purchases", "buy", "retail", "wishlist"],
  nature: ["leaf", "eco", "green", "environment"],
  tools: ["repairs", "maintenance", "fix", "diy", "spanner"],
  sparkles: ["beauty", "skincare", "skin care", "makeup", "hair", "nails", "self care", "glow", "magic", "special"],
  baby: ["kids", "child", "children", "infant", "newborn", "pregnancy", "parenting"],
  bike: ["bicycle", "cycling", "ride"],
  building: ["apartment", "office", "property", "city"],
  camera: ["photos", "photography", "pictures"],
  cat: ["cats", "kitten", "pet"],
  coffee: ["cafe", "cafes", "espresso", "tea"],
  flower: ["flowers", "garden", "plants", "bloom"],
  gem: ["jewellery", "jewelry", "valuables", "diamond", "precious"],
  globe: ["world", "countries", "international", "languages"],
  hammer: ["diy", "renovation", "building", "repairs", "construction"],
  headphones: ["music", "audio", "podcasts", "listening"],
  wellness: ["health", "medical", "heart", "blood pressure", "wellbeing"],
  keys: ["key", "property", "rental", "access", "passwords"],
  library: ["books", "collection", "archive", "reading"],
  music: ["songs", "albums", "playlist", "concerts", "band"],
  star: ["favourites", "important", "rating", "reviews"],
  telescope: ["astronomy", "stars", "space", "explore"],
  camping: ["camp", "tent", "outdoors", "hiking"],
  outdoors: ["trees", "forest", "nature", "bush", "hiking"],
  trophy: ["achievements", "awards", "wins", "competition"],
  umbrella: ["insurance", "rain", "cover", "protection"],
  wallet: ["money", "cards", "budget", "spending", "cash"],
  watch: ["time", "watches", "smartwatch"],
  water: ["swimming", "beach", "surf", "ocean", "sea", "pool"],
  activity: ["health", "heart rate", "tracking", "vitals", "stats"],
  alarm: ["reminders", "wake", "time", "schedule"],
  apple: ["fruit", "nutrition", "diet", "healthy eating"],
  money: ["finance", "dollar", "cash", "income", "salary", "pay"],
  drinks: ["beer", "bar", "pub", "alcohol", "brewery"],
  bird: ["birds", "birdwatching", "pet"],
  bone: ["dog", "pet", "bones", "skeleton"],
  robot: ["ai", "automation", "tech", "bot"],
  celebrations: ["birthday", "birthdays", "cake", "anniversary", "party"],
  calculator: ["maths", "math", "budget", "tax", "accounting", "numbers"],
  faith: ["religion", "church", "worship", "prayer", "spiritual"],
  weather: ["forecast", "sunny", "climate", "season"],
  coding: ["code", "programming", "developer", "software"],
  compass: ["explore", "direction", "adventure", "navigation"],
  cooking: ["cook", "recipes", "kitchen", "meals", "meal prep"],
  crown: ["vip", "premium", "best", "royal"],
  dog: ["dogs", "puppy", "pet", "walks"],
  drill: ["diy", "tools", "renovation", "repairs"],
  factory: ["manufacturing", "industry", "production"],
  movies: ["films", "film", "cinema", "watchlist", "tv shows"],
  fish: ["fishing", "aquarium", "seafood"],
  science: ["experiments", "lab", "chemistry", "research"],
  guitar: ["music", "instrument", "lessons", "band"],
  hospital: ["medical", "emergency", "surgery", "health"],
  laptop: ["computer", "tech", "devices", "work"],
  ideas: ["idea", "brainstorm", "inspiration", "lightbulb", "thoughts"],
  maps: ["places", "locations", "trips", "travel", "route"],
  medal: ["achievements", "awards", "competition", "race"],
  microscope: ["science", "research", "lab", "biology"],
  mountains: ["hiking", "climbing", "skiing", "trek", "outdoors"],
  notebook: ["notes", "journal", "diary", "planner", "notebook"],
  party: ["parties", "events", "celebration", "celebrations"],
  medicine: ["medication", "meds", "prescriptions", "pharmacy", "tablets", "pills"],
  pizza: ["takeaway", "food", "fast food"],
  rocket: ["launch", "startup", "projects", "space"],
  crafts: ["sewing", "craft", "diy", "scrapbooking", "knitting"],
  security: ["safety", "protection", "privacy", "passwords"],
  furniture: ["home", "decor", "interior", "couch", "living room"],
  doctor: ["gp", "dentist", "dental", "medical", "appointments", "health", "specialist", "physio"],
  tickets: ["events", "concerts", "shows", "bookings"],
  train: ["commute", "transport", "public transport", "rail", "trains"],
  sports: ["sport", "team", "volleyball", "netball", "soccer", "football"],
  wine: ["wines", "cellar", "drinks", "winery"],
  energy: ["electricity", "power", "energy bill", "solar"],
  person: ["me", "personal", "self", "contact"],
  profile: ["me", "personal", "profile", "account"],
  people: ["family", "friends", "team", "group", "contacts"],
  standing: ["posture", "yoga", "body", "stretching"],
  accessibility: ["disability", "wheelchair", "ndis", "support", "care"],
  woman: ["women", "female", "her", "womens health"],
  man: ["men", "male", "him", "mens health"],
  contacts: ["address book", "people", "network", "business cards"],
  community: ["friends", "volunteering", "network", "club", "social"],
  strength: ["gym", "strength training", "muscle", "lifting"],
  walking: ["steps", "walks", "running", "hiking"],
  theatre: ["drama", "shows", "acting", "performances", "musicals"],
  phone: ["mobile", "phone plan", "iphone", "android", "devices"],
  tablet: ["ipad", "devices", "reading"],
  computer: ["pc", "desktop", "devices", "screen"],
  keyboard: ["typing", "computer", "peripherals"],
  mouse: ["computer", "peripherals"],
  television: ["tv", "streaming", "shows", "netflix", "series"],
  processor: ["hardware", "computer", "chip", "tech"],
  terminal: ["command line", "developer", "server"],
  code: ["programming", "website", "html", "developer"],
  braces: ["code", "programming", "json"],
  binary: ["data", "computing", "tech"],
  database: ["data", "records", "storage", "backups"],
  development: ["git", "projects", "version control", "branches"],
  gavel: ["legal", "law", "court", "lawyer", "fines"],
  scale: ["legal", "balance", "justice", "fairness", "decisions"],
  analytics: ["stats", "statistics", "charts", "progress", "tracking", "reports"],
  done: ["completed", "finished", "checklist", "tasks"],
  blocked: ["avoid", "stop", "quit", "banned"],
  chat: ["messages", "conversations", "notes", "talk"],
  pinned: ["important", "saved", "board"],

  // Everyday life admin.
  car: ["vehicle", "auto", "rego", "registration", "service", "servicing", "mechanic", "parking", "tyres", "driving"],
  fuel: ["petrol", "gas", "diesel", "fuel station", "ev", "charging"],
  bus: ["transport", "public transport", "commute", "school bus", "coach"],
  boat: ["sailing", "yacht", "marina", "boating", "kayak"],
  bills: ["receipt", "receipts", "invoice", "invoices", "payments", "utilities", "expenses", "tax"],
  card: ["credit card", "debit card", "bank", "banking", "payments", "cards"],
  subscriptions: ["subscription", "membership", "memberships", "recurring", "renewals", "streaming"],
  insurance: ["cover", "policy", "policies", "warranty", "warranties", "health insurance", "car insurance", "protection"],
  savings: ["save", "piggy bank", "emergency fund", "goals", "super", "superannuation"],
  investing: ["investments", "shares", "stocks", "portfolio", "growth", "crypto", "super"],
  coins: ["money", "cash", "change", "budget", "spending"],
  electricity: ["power", "electricity bill", "plug", "electrician", "appliances"],
  wifi: ["internet", "nbn", "broadband", "router", "network"],
  gas: ["gas bill", "heating", "fire", "fireplace", "bbq", "streak"],
  droplet: ["water", "water bill", "hydration", "plumber", "plumbing"],
  bath: ["bathroom", "plumbing", "self care", "spa"],
  lamp: ["lighting", "lights", "decor", "bedroom"],
  cleaning: ["clean", "chores", "housework", "cleaner", "spray"],
  laundry: ["washing", "washing machine", "clothes", "chores", "dry cleaning"],
  recycling: ["recycle", "bins", "rubbish", "waste", "eco"],
  plants: ["plant", "houseplants", "seedlings", "garden", "watering"],
  garden: ["gardening", "yard", "lawn", "landscaping", "veggie patch"],
  groceries: ["grocery", "supermarket", "shopping list", "pantry", "food shopping"],
  vegetables: ["veggies", "veg", "produce", "farmers market", "healthy eating"],
  recipes: ["recipe", "cooking", "chef", "meal plan", "meal planning", "baking"],
  salad: ["healthy", "diet", "nutrition", "meals", "lunch"],
  night: ["sleep", "moon", "bedtime", "night routine", "dreams"],
  sleep: ["bed", "bedroom", "rest", "naps", "sleep tracking"],
  mood: ["feelings", "emotions", "mental health", "happiness", "wellbeing", "smile"],
  journal: ["journaling", "diary", "writing", "notes", "reflection", "gratitude"],
  writing: ["write", "poetry", "stories", "blog", "author"],
  mind: ["mental health", "meditation", "mindfulness", "therapy", "brain", "focus"],
  sun: ["summer", "sunshine", "morning", "morning routine", "outdoors"],
  timer: ["time tracking", "pomodoro", "focus", "stopwatch"],
  hourglass: ["deadlines", "waiting", "countdown", "time"],
  target: ["goals", "habits", "aims", "focus", "objectives"],
  school: ["kids", "homework", "classes", "teachers", "education"],
  backpack: ["school", "bag", "hiking", "travel", "uni"],
  store: ["shop", "small business", "side hustle", "market", "retail"],
  handshake: ["deals", "clients", "partners", "agreements", "contracts", "networking"],
  moving: ["move", "removalists", "truck", "delivery", "relocation"],
  storage: ["boxes", "packing", "storage unit", "inventory", "declutter"],
  warehouse: ["inventory", "stock", "storage", "shed"],
  archive: ["records", "old", "past", "history", "keepsakes"],
  folder: ["documents", "files", "paperwork", "records"],
  identity: ["id", "id card", "passport", "licence", "license", "visa", "medicare"],
  lock: ["passwords", "security", "private", "accounts", "logins"],
  podcast: ["podcasts", "radio", "audio", "episodes", "listening"],
  microphone: ["singing", "karaoke", "recording", "voice", "speaking"],
  popcorn: ["movies", "movie night", "watchlist", "cinema", "snacks"],
  news: ["newspaper", "articles", "reading list", "magazines", "current events"],
  painting: ["paint", "art", "painter", "decorating", "renovation"],
  design: ["graphic design", "illustration", "drawing", "sketching", "creative"],
  ruler: ["measurements", "sizes", "renovation", "diy", "planning"],
  beach: ["holiday", "vacation", "tropical", "island", "summer"],
  winter: ["snow", "skiing", "cold", "christmas", "seasonal"],
  puzzle: ["puzzles", "jigsaw", "board games", "brain games", "problem solving"],
  dice: ["board games", "tabletop", "games night", "dnd", "luck"],
  events: ["event", "dates", "anniversaries", "weddings", "special days", "occasions"],
  calendar: ["dates", "schedule", "planner", "appointments", "bookings"],
  ribbon: ["awareness", "charity", "cause", "donations", "fundraising"],
} as const satisfies Record<CustomModuleIconName, readonly string[]>;
