import type { NextConfig } from "next";

const isDevelopment = process.env.NODE_ENV === "development";

// A same-origin address for the two reporting mechanisms below -- see
// app/api/csp-report/route.ts. Without one, "keep this in report-only mode
// until reports confirm all required sources are represented" is a
// condition that can never be met: nothing collects the reports, so nothing
// can ever confirm anything, and report-only mode never has a way to
// graduate to actually enforced.
const CSP_REPORT_ENDPOINT = "/api/csp-report";
const CSP_REPORT_GROUP = "csp-endpoint";

// Keep this policy in report-only mode until a soak period of real reports
// shows nothing unexpected. Next.js currently emits inline bootstrap
// scripts, and the application uses inline styles generated by the runtime.
const contentSecurityPolicy = [
  "default-src 'self'",
  `script-src 'self' 'unsafe-inline'${isDevelopment ? " 'unsafe-eval'" : ""}`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' blob: data:",
  "font-src 'self' data:",
  "connect-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  // Both reporting mechanisms, since browser support for each is
  // inconsistent: report-uri is the older directive with the broadest
  // support (still the only one some browsers honour); report-to is the
  // modern Reporting API, paired with the Reporting-Endpoints header below
  // that actually names the endpoint it refers to.
  `report-uri ${CSP_REPORT_ENDPOINT}`,
  `report-to ${CSP_REPORT_GROUP}`,
].join("; ");

const securityHeaders = [
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  {
    key: "Permissions-Policy",
    value:
      "camera=(), microphone=(), geolocation=(), payment=(), usb=(), browsing-topics=()",
  },
  { key: "X-Frame-Options", value: "DENY" },
  { key: "Content-Security-Policy-Report-Only", value: contentSecurityPolicy },
  { key: "Reporting-Endpoints", value: `${CSP_REPORT_GROUP}="${CSP_REPORT_ENDPOINT}"` },
];

const nextConfig: NextConfig = {
  async headers() {
    return [
      {
        source: "/:path*",
        headers: securityHeaders,
      },
      {
        // Every HTML route currently contains private, user-specific data.
        // Exclude APIs and framework assets so their cache semantics remain
        // independently configurable.
        source:
          "/((?!api(?:/|$)|_next/static(?:/|$)|_next/image(?:/|$)|favicon.ico$|icon.png$).*)",
        headers: [{ key: "Cache-Control", value: "private, no-store" }],
      },
      {
        source: "/api/notifications/evaluate",
        headers: [{ key: "Cache-Control", value: "private, no-store" }],
      },
    ];
  },
};

export default nextConfig;
