-- Replace the legacy fixed owner/settings identifiers with generated UUIDs.
-- User foreign keys use ON UPDATE CASCADE, so changing the owner primary key
-- preserves every existing ownership relation atomically.
UPDATE "User"
SET "id" = gen_random_uuid()::text
WHERE "id" = 'current';

UPDATE "UserSettings"
SET "id" = gen_random_uuid()::text
WHERE "id" = 'current';

-- Prisma's uuid() default is generated by Prisma Client rather than PostgreSQL.
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "UserSettings" ALTER COLUMN "id" DROP DEFAULT;
